### ISSUE TITLE
Stuck at loading

### ISSUE THREAD

**Issue by sleroq** [snowfallorg/nix-software-center#20]
** Info
On first launch I set `flake.nix` to `~/.config/nixpkgs/flake.nix` and left `configuration.nix` as is.
I'm on nixOS unstable

** Error
```
 ERROR nix_software_center::ui::windowloading > Error getting NixOS pkgs: Failed to download latest packages.json
```

**Comment by eclairevoyant** [comment]
related to #14?

**Comment by sleroq** [comment]
Issue is not relevant.
