### ISSUE TITLE
FR: display version

### ISSUE THREAD

**Issue by Zahrun** [snowfallorg/nix-software-center#34]
Would be nice to see which version of the package/software we are installing

**Comment by tobiasBora** [comment]
I can see it in the title like:

![image](https://github.com/snowfallorg/nix-software-center/assets/2164118/5179facf-c284-4f64-b550-d4daadb258b4)

Is it what you want?

**Comment by Zahrun** [comment]
Yes that is fine actually. I’m not sure if I had missed it at the time or if something changed in between.
