### ISSUE TITLE
allow configuring icons

### ISSUE THREAD

**Issue by KiaraGrouwstra** [snowfallorg/nix-software-center#53]
hi there,
thanks for making this!
this might be a bit of a nitpick, but i was wondering if it might be possible to allow configuring the icon set used for the software in the store.
e.g. i'm personally using [papirus icons](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) in nixos now, and imagine others might have icon sets they like as well.
i thought it might be possible to user a system-provided icon set, although maybe another way could be to have a configuration allowing to set preferences like this.

**Comment by pinkcreeper100** [comment]
I'm not sure where the icons are grabbed from, but I have a feeling that they might be being pulled directly from nixpkgs

**Comment by KiaraGrouwstra** [comment]
i was thinking about just [overriding the font](https://github.com/KiaraGrouwstra/nix-software-center/compare/main...papirus-icon-theme) tho i'm having trouble getting it to load the explore categories, so this may not have worked

**Comment by KiaraGrouwstra** [comment]
oh i think home-manager's `gtk.iconTheme` does this
